### Header versioning (old)

# GET V1
GET http://localhost:8081/api/animals-old-header
X-API-Version: v1

###
# GET V1
GET http://localhost:8081/api/animals-old-header
X-API-Version: v2

###
# GET Default
GET http://localhost:8081/api/animals-old-header



### Header versioning (new)

# GET V1
GET http://localhost:8081/api/animals
X-API-Version: v1

###
# GET V2
GET http://localhost:8081/api/animals
X-API-Version: v2

###
# GET V1.1
GET http://localhost:8081/api/animals
X-API-Version: v1.1

###
# GET Individual animal V1
GET http://localhost:8081/api/animals/1
X-API-Version: v1

###
# POST V1
POST http://localhost:8081/api/animals
X-API-Version: v1
Content-Type: text/plain

Monkey

###
# Default - no header
GET http://localhost:8081/api/animals

###
# Invalid version
GET http://localhost:8081/api/animals
X-API-Version: v99

###
# Alternative header name
GET http://localhost:8081/api/animals
API-Version: v1

###
# Case sensitivity
GET http://localhost:8081/api/animals
x-api-version: v1

###
# Multiple headers
GET http://localhost:8081/api/animals
X-API-Version: v2
Accept: application/json
